Repository Nefry-Community/TutorialBook, pull requests merged in 2018-04, with the labels that each got.

#17 Pokiiio 02ArduinoSetting
  articles/02ArduinoSetting.re
  articles/images/02ArduinoSetting/arduino_ide_donation.png
  articles/images/02ArduinoSetting/arduino_ide_download.png
  articles/images/02ArduinoSetting/arduino_ide_mac.jpg
  articles/images/02ArduinoSetting/arduino_ide_main.png
  articles/images/02ArduinoSetting/arduino_ide_win_app_store.png
  articles/images/02ArduinoSetting/arduino_ide_win_installer.png
  articles/images/02ArduinoSetting/arduino_ide_win_installer2.png
  articles/images/02ArduinoSetting/arduino_ide_win_zip.png
  articles/images/02ArduinoSetting/nefry_version.png
  articles/md/8-nefrybt-arduino-ide-setup2.md
Labels: 再レビュー待ち

#19 リンク情報更新
  articles/21NefryLink.re
Labels: レビュー待ち

#23 04DefaultSW 執筆初動
  articles/03DefaultLed.re
  articles/04DefaultSW.re
  articles/images/03DefaultLed/03DefaultLed_01.jpg
  articles/images/03DefaultLed/03DefaultLed_02.png
  articles/images/03DefaultLed/03DefaultLed_03.png
  articles/images/03DefaultLed/ide01.png
  articles/images/03DefaultLed/ide02.png
  articles/images/04DefaultSW/04DefaultSW_01.png
  articles/images/04DefaultSW/04DefaultSW_02.png
  articles/images/04DefaultSW/04DefaultSW_03.png
  articles/images/04DefaultSW/04DefaultSW_04.png
  articles/md/03DefaultLed.re.md
  articles/md/04DefaultSW.re.md
Labels: 再レビュー待ち

#37 無線LAN設定
  articles/11NefryWiFi.re
Labels: レビュー待ち

#34 Tipsを追加
  articles/20Tips.re
  articles/md/8-nefrybt-library.md
Labels: レビュー待ち

#33 19章 Nefry BT ライブラリ紹介です
  articles/19Library.re
  articles/catalog.yml
  articles/images/19Library/ambient_detail.png
  articles/images/19Library/ambient_top.png
  articles/images/19Library/azureiothub_detail.png
  articles/images/19Library/azureiothub_top.png
  articles/images/19Library/display1.jpg
  articles/images/19Library/display2.jpg
  articles/images/19Library/display3.jpg
  articles/images/19Library/display4.jpg
  articles/images/19Library/display5.jpg
  articles/images/19Library/fastsensing_add_stub_device.png
  articles/images/19Library/fastsensing_detail.png
  articles/images/19Library/fastsensing_developer_program.png
  articles/images/19Library/fastsensing_top.png
  articles/images/19Library/firebase_database_choose.png
  articles/images/19Library/firebase_database_host.png
  articles/images/19Library/firebase_database_result.png
  articles/images/19Library/firebase_database_secret.png
  articles/images/19Library/firebase_top.png
  articles/images/19Library/thingspeak_channel_detail.png
  articles/images/19Library/thingspeak_detail.png
  articles/images/19Library/thingspeak_top.png
  articles/md/8-nefrybt-library2.md
Labels: レビュー待ち

#36 Default program
  articles/10DefaultProgram.re
  articles/images/10DefaultProgram/ifttt.png
  articles/images/10DefaultProgram/linenotify.png
Labels: レビュー待ち

#35 セットアップ章作成
  articles/01NefrySetup.re
  articles/images/01NefrySetup/NefryDisplay.png
  articles/images/01NefrySetup/package1.jpg
  articles/images/01NefrySetup/package2.jpg
Labels: レビュー待ち

#21 Ifttt
  articles/12IFTTT.re
Labels: レビュー待ち

#20 LineNotify修正
  articles/13LineNotify.re
  articles/images/13LineNotify/line02.png
  articles/images/13LineNotify/line03.png
Labels: レビュー待ち

#18 前書き内容修正
  articles/preface.re
Labels: レビュー待ち

#28 06SerialPlotter
  articles/06SerialPlotter.re
  articles/images/06SerialPlotter/06SerialPlotter_01.png
  articles/images/06SerialPlotter/06SerialPlotter_02.png
  articles/images/06SerialPlotter/06SerialPlotter_03.png
  articles/images/06SerialPlotter/06SerialPlotter_04.png
  articles/images/06SerialPlotter/06SerialPlotter_05.png
  articles/images/06SerialPlotter/06SerialPlotter_06.png
  articles/images/06SerialPlotter/06SerialPlotter_07.png
  articles/images/06SerialPlotter/06SerialPlotter_08.png
  articles/images/06SerialPlotter/06SerialPlotter_09.png
  articles/images/06SerialPlotter/06SerialPlotter_10.png
  articles/md/06SerialPlotter.re.md
Labels: レビュー待ち

#45 review: 03
  articles/03DefaultLed.re
Labels: レビュー修正

#46 review: 04
  articles/04DefaultSW.re
Labels: レビュー修正

#47 Review05
  articles/05DigitalLed.re
Labels: レビュー修正

#50 review: 06
  articles/06SerialPlotter.re
Labels: レビュー修正

#44 review: 02
  articles/02NefryProgram.re
  articles/images/02NefryProgram/image7.png
  articles/images/02NefryProgram/image8.png
  articles/images/02NefryProgram/image9.png
Labels: レビュー修正

#56 review: 21
  articles/21NefryLink.re
Labels: レビュー修正

#52 Review10
  articles/10DefaultProgram.re
Labels: レビュー修正

#51 Review11
  articles/11NefryWiFi.re
Labels: レビュー修正

#55 review: 20
  articles/20Tips.re
Labels: レビュー修正

#54 review: 19
  articles/19Library.re
Labels: レビュー修正

#57 review: preface
  articles/preface.re
Labels: レビュー修正

#67 review: 13
  articles/13LineNotify.re
Labels: レビュー修正

#66 review: 12
  articles/12IFTTT.re
Labels: レビュー修正

#65 review: タイトルの語感を統一
  articles/00start.re
  articles/01NefrySetup.re
  articles/02ArduinoSetting.re
  articles/05DigitalLed.re
  articles/06SerialPlotter.re
Labels: レビュー待ち
